<link rel="stylesheet" href="/css/error.css">
<div class="d-flex flex-column fill-parent">
    <div class="flex-fill d-flex flex-column justify-content-center align-items-center">
        <div class="d-flex flex-column rounded-circle bg-danger error-icon">
            <div class="m-auto text-white text-center">
                <p class="m-0">Error</p>
                <h1 class="m-0">501</h1>
            </div>
        </div>
        <h2 class="mt-1">Not Implemented</h2>
        <a href="javascript: history.back()">Go back...</a>
        <a href="/">Return to index...</a>
    </div>
</div>